# Generated by Django 4.1.3 on 2022-11-24 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Adverts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("platform_name", models.TextField()),
                ("platform_fee", models.DecimalField(decimal_places=2, max_digits=6)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Properties",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("guest_limit", models.IntegerField()),
                ("bathrooms", models.IntegerField()),
                ("pets", models.BooleanField()),
                ("activation_date", models.DateField()),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reservations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=30)),
                ("check_in", models.DateField()),
                ("check_out", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("comments", models.TextField()),
                ("guests_number", models.IntegerField()),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "ad_belongs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.adverts"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="adverts",
            name="property",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.properties"
            ),
        ),
    ]
