# Generated by Django 4.1.3 on 2022-11-27 18:29

import app.utils
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("app", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="adverts", name="name"),
        migrations.RemoveField(model_name="properties", name="name"),
        migrations.RemoveField(model_name="reservations", name="name"),
        migrations.AddField(
            model_name="properties",
            name="code",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=30, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reservations",
            name="code",
            field=models.CharField(
                default=app.utils.gerar_hash,
                editable=False,
                max_length=30,
                unique=True,
            ),
        ),
    ]
