# Generated by Django 4.1.3 on 2022-11-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="reservations",
            name="code",
            field=models.CharField(default=913, editable=False, max_length=250),
        )
    ]
