# Generated by Django 4.1.3 on 2022-11-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("app", "0002_alter_reservations_code")]

    operations = [
        migrations.RemoveField(model_name="adverts", name="name"),
        migrations.RemoveField(model_name="properties", name="name"),
        migrations.RemoveField(model_name="reservations", name="name"),
        migrations.AlterField(
            model_name="reservations",
            name="code",
            field=models.CharField(max_length=30),
        ),
    ]
