# Generated by Django 4.1.3 on 2022-11-26 15:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("app", "0003_remove_adverts_name_remove_properties_name_and_more")]

    operations = [
        migrations.AddField(
            model_name="properties",
            name="code",
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        )
    ]
